# Generated by Django 5.0.14 on 2026-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
