[mypy]
python_version = 3.12
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

strict = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
check_untyped_defs = True
disallow_untyped_defs = False

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

[mypy-*.migrations.*]
ignore_errors = True

[mypy-manage]
ignore_errors = True
