# Generated by Django 5.0.14 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="aggregate_key",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregate_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "aggregate_key"], name="notificatio_recipie_aggkey_idx"),
        ),
    ]
