# Generated by Django 5.0.14 on 2026-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_aggregate_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_ce0b79_idx',
            old_name='notificatio_recipie_aggkey_idx',
        ),
    ]
