# Generated by Django 5.0.14 on 2026-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
