# Generated by Django 5.2.10 on 2026-01-30 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantBranding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company_name",
                    models.CharField(
                        help_text="Nome customizado da empresa (pode diferir do Company.name)", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo da empresa (PNG/SVG, max 2MB)",
                        null=True,
                        upload_to="branding/logos/",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Ícone/favicon (ICO/PNG, recomendado 32x32 ou 64x64)",
                        null=True,
                        upload_to="branding/icons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0C4B33", help_text="Cor primária em hexadecimal (ex: #0C4B33)", max_length=7
                    ),
                ),
                (
                    "theme_palette",
                    models.CharField(
                        choices=[
                            ("django-green", "Django Green"),
                            ("ocean-blue", "Ocean Blue"),
                            ("royal-purple", "Royal Purple"),
                            ("sunset-orange", "Sunset Orange"),
                            ("forest-green", "Forest Green"),
                            ("slate-gray", "Slate Gray"),
                        ],
                        default="django-green",
                        help_text="Paleta de cores pré-estabelecida",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="theme_branding", to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Branding",
                "verbose_name_plural": "Tenant Brandings",
            },
        ),
    ]
