# Generated by Django 5.0.14 on 2026-01-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tenantbranding"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbranding",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="footer_text",
            field=models.CharField(
                blank=True, help_text="Texto exibido no rodapé (ex: Todos os direitos reservados)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TenantEmailConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "use_custom_smtp",
                    models.BooleanField(
                        default=False,
                        help_text="Se ativado, utiliza as configurações abaixo em vez do SMTP padrão do sistema.",
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(default=587)),
                ("smtp_user", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.CharField(blank=True, help_text="Senha do servidor SMTP", max_length=255)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, help_text="E-mail remetente (ex: contato@empresa.com)", max_length=254
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="email_config", to="core.company"
                    ),
                ),
            ],
        ),
    ]
