# Generated by Django 5.0.14 on 2026-02-01 22:05

from django.db import migrations, models

import shared_kernel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_tenantbranding_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantbranding",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Ícone/favicon (ICO/PNG, max 2MB, recomendado 32x32 ou 64x64)",
                null=True,
                upload_to="branding/icons/",
                validators=[shared_kernel.validators.validate_avatar],
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo da empresa (PNG/JPEG/WebP, max 10MB)",
                null=True,
                upload_to="branding/logos/",
                validators=[shared_kernel.validators.validate_image],
            ),
        ),
    ]
