# Generated by Django 5.0.14 on 2026-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_tenantbranding_icon_alter_tenantbranding_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="onboarding_step",
            field=models.IntegerField(default=1),
        ),
    ]
