# Generated by Django 5.2.11 on 2026-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_company_onboarding_completed_company_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbranding",
            name="background_color",
            field=models.CharField(
                default="#FFFFFF", help_text="Cor de fundo em hexadecimal (ex: #FFFFFF)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="custom_css",
            field=models.TextField(blank=True, help_text="Custom CSS para ser injetado no cabeçalho"),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="custom_js",
            field=models.TextField(blank=True, help_text="Custom JS para ser injetado antes do fechamento do body"),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="font_family",
            field=models.CharField(
                default="Inter", help_text="Nome da Fonte Google (ex: Inter, Roboto, Montserrat)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="secondary_color",
            field=models.CharField(
                default="#111827", help_text="Cor secundária em hexadecimal (ex: #111827)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="theme_palette",
            field=models.CharField(
                choices=[
                    ("django-green", "Django Green"),
                    ("ocean-blue", "Ocean Blue"),
                    ("royal-purple", "Royal Purple"),
                    ("sunset-orange", "Sunset Orange"),
                    ("forest-green", "Forest Green"),
                    ("slate-gray", "Slate Gray"),
                ],
                default="django-green",
                help_text="Paleta de cores pré-estabelecida (opcional se usar cores customizadas)",
                max_length=50,
            ),
        ),
    ]
