# Generated by Django 5.0.14 on 2026-02-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False, help_text="Ativar autenticação LDAP para esta empresa")),
                (
                    "server_uri",
                    models.CharField(
                        blank=True,
                        help_text="URI do servidor LDAP (ex: ldap://ldap.empresa.com:389 ou ldaps://ldap.empresa.com:636)",
                        max_length=255,
                    ),
                ),
                (
                    "bind_dn",
                    models.CharField(
                        blank=True, help_text="DN para bind (ex: cn=admin,dc=empresa,dc=com)", max_length=255
                    ),
                ),
                (
                    "bind_password_encrypted",
                    models.BinaryField(blank=True, help_text="Senha do bind DN (criptografada)", null=True),
                ),
                (
                    "user_search_base",
                    models.CharField(
                        blank=True,
                        help_text="Base DN para buscar usuários (ex: ou=users,dc=empresa,dc=com)",
                        max_length=255,
                    ),
                ),
                (
                    "user_search_filter",
                    models.CharField(
                        default="(uid=%(user)s)",
                        help_text="Filtro de busca LDAP - use %(user)s como placeholder",
                        max_length=255,
                    ),
                ),
                (
                    "attr_username",
                    models.CharField(default="uid", help_text="Atributo LDAP para username", max_length=50),
                ),
                ("attr_email", models.CharField(default="mail", help_text="Atributo LDAP para email", max_length=50)),
                (
                    "attr_first_name",
                    models.CharField(default="givenName", help_text="Atributo LDAP para primeiro nome", max_length=50),
                ),
                (
                    "attr_last_name",
                    models.CharField(default="sn", help_text="Atributo LDAP para sobrenome", max_length=50),
                ),
                ("use_tls", models.BooleanField(default=True, help_text="Usar StartTLS para conexão segura")),
                (
                    "require_group",
                    models.CharField(
                        blank=True, help_text="DN do grupo LDAP obrigatório para acesso (opcional)", max_length=255
                    ),
                ),
                (
                    "admin_group_dn",
                    models.CharField(
                        blank=True, help_text="DN do grupo LDAP para administradores (opcional)", max_length=255
                    ),
                ),
                (
                    "last_test_status",
                    models.CharField(
                        choices=[("success", "Sucesso"), ("failed", "Falha"), ("pending", "Pendente")],
                        default="pending",
                        help_text="Status do último teste de conexão",
                        max_length=20,
                    ),
                ),
                ("last_test_message", models.TextField(blank=True, help_text="Mensagem do último teste de conexão")),
                ("last_test_at", models.DateTimeField(blank=True, help_text="Data/hora do último teste", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ldap_config", to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração LDAP",
                "verbose_name_plural": "Configurações LDAP",
            },
        ),
    ]
