# Generated by Django 5.2.11 on 2026-03-02 11:42

from django.db import migrations, models

import shared_kernel.utils
import shared_kernel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_smtp_password_plaintext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantbranding",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Ícone/favicon (ICO/PNG, max 2MB, recomendado 32x32 ou 64x64)",
                null=True,
                upload_to=shared_kernel.utils.TenantUploadTo("branding/icons"),
                validators=[shared_kernel.validators.validate_avatar],
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo da empresa (PNG/JPEG/WebP, max 10MB)",
                null=True,
                upload_to=shared_kernel.utils.TenantUploadTo("branding/logos"),
                validators=[shared_kernel.validators.validate_image],
            ),
        ),
    ]
