# Generated by Django 5.2.10 on 2026-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
