# Generated by Django 5.0.14 on 2026-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_page_meta_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[("draft", "Rascunho"), ("published", "Publicado")],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
