# Generated by Django 5.0.14 on 2026-03-30 17:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('pages', '0004_remove_is_published'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='page_title_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='page_content_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
