# Generated by Django 5.2.11 on 2026-02-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_company_onboarding_completed_company_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Integração Site Externo", max_length=100, verbose_name="Nome da Chave"
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=16, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=128)),
                ("scopes", models.JSONField(default=list, verbose_name="Escopos de Acesso")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Expira em")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Último Uso")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
            ],
            options={
                "verbose_name": "Chave de API",
                "verbose_name_plural": "Chaves de API",
                "ordering": ["-created_at"],
            },
        ),
    ]
