# Generated by Django 5.0.14 on 2026-02-01 22:05

from django.db import migrations, models

import shared_kernel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_message_file_message_file_name_message_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Anexo (Imagens/Documentos, max 5MB)",
                null=True,
                upload_to="chat/attachments/",
                validators=[shared_kernel.validators.validate_chat_file],
            ),
        ),
    ]
