# Generated by Django 5.0.14 on 2026-02-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_ldap_config"),
        ("messenger", "0006_message_edited_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created_at"], name="messenger_m_convers_14169e_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "is_read", "sender"], name="messenger_m_convers_562a60_idx"),
        ),
        migrations.AddField(
            model_name="conversationpreference",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company"),
        ),
        migrations.AddField(
            model_name="conversationpreference",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="messenger.conversation"
            ),
        ),
        migrations.AddField(
            model_name="conversationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="conversationpreference",
            index=models.Index(fields=["user", "is_pinned"], name="messenger_c_user_id_c3901c_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationpreference",
            index=models.Index(fields=["user", "is_muted"], name="messenger_c_user_id_880d4c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="conversationpreference",
            unique_together={("user", "conversation")},
        ),
    ]
