# Generated by Django 5.0.14 on 2026-02-27 19:55

import shared_kernel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_conversationpreference_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, help_text='Anexo (Imagens/Documentos, max 10MB)', null=True, upload_to='chat/attachments/', validators=[shared_kernel.validators.validate_chat_file]),
        ),
    ]
