# Generated by Django 5.2.11 on 2026-03-02 11:42

from django.db import migrations, models

import shared_kernel.utils
import shared_kernel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0008_alter_message_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Anexo (Imagens/Documentos, max 10MB)",
                null=True,
                upload_to=shared_kernel.utils.TenantUploadTo("chat/attachments"),
                validators=[shared_kernel.validators.validate_chat_file],
            ),
        ),
    ]
