# Generated by Django 5.0.14 on 2026-03-04 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0010_contactblock"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactblock",
            new_name="messenger_c_blocker_13a1d2_idx",
            old_name="messenger_c_blocker_54c0fa_idx",
        ),
    ]
