# Generated by Django 5.0.14 on 2026-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_conversationpreference_user_is_archived_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationpreference',
            new_name='messenger_c_user_id_58f83d_idx',
            old_name='messenger_c_user_id_d4ed4f_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationpreference',
            new_name='messenger_c_user_id_d8bf68_idx',
            old_name='messenger_c_user_id_4bd6fb_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedelivery',
            new_name='messenger_m_message_639dff_idx',
            old_name='messenger_m_message_87a2e9_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedelivery',
            new_name='messenger_m_user_id_1e3d56_idx',
            old_name='messenger_m_user_id_4f3b38_idx',
        ),
        migrations.RenameIndex(
            model_name='messageread',
            new_name='messenger_m_message_c19e79_idx',
            old_name='messenger_m_message_9e5d89_idx',
        ),
        migrations.RenameIndex(
            model_name='messageread',
            new_name='messenger_m_user_id_fb0bf1_idx',
            old_name='messenger_m_user_id_03833c_idx',
        ),
    ]
