# Generated by Django 5.2.10 on 2026-01-29 17:41

import shared_kernel.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_kernel.utils.TenantUploadTo('articles')),
        ),
    ]
