# Generated by Django 5.2.10 on 2026-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
