# Generated by Django 5.0.14 on 2026-02-01 22:05

import django.db.models.deletion
from django.db import migrations, models

import shared_kernel.utils
import shared_kernel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_meta_description_article_meta_keywords_and_more"),
        ("core", "0006_alter_tenantbranding_icon_alter_tenantbranding_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Imagem de destaque (max 10MB, formatos: JPEG, PNG, GIF, WebP)",
                null=True,
                upload_to=shared_kernel.utils.TenantUploadTo("articles"),
                validators=[shared_kernel.validators.validate_image],
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company"),
                ),
            ],
            options={
                "unique_together": {("company", "slug")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="articles.tag"),
        ),
    ]
