# Generated by Django 5.0.14 on 2026-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_articleview"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("pending", "Aguardando Aprovação"),
                    ("published", "Publicado"),
                    ("rejected", "Rejeitado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
