# Generated by Django 5.0.14 on 2026-03-17

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_public_comments(apps, schema_editor):
    Comment = apps.get_model("articles", "Comment")
    Comment.objects.filter(author__isnull=True).update(is_public=True)


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="articles.comment",
            ),
        ),
        migrations.RunPython(mark_existing_public_comments, migrations.RunPython.noop),
    ]
