# Generated by Django 5.0.14 on 2026-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_comment_created_at_alter_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando Revisão'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('rejected', 'Rejeitado')], default='draft', max_length=20),
        ),
    ]
