# Generated by Django 5.0.14 on 2026-03-06 18:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0014_company_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                (
                    "rrule",
                    models.TextField(blank=True, help_text="Regra de recorrência no formato RFC 5545", null=True),
                ),
                (
                    "color_category",
                    models.CharField(default="blue", help_text="Cor do evento no calendário", max_length=50),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("meeting_url", models.URLField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "indexes": [
                    models.Index(
                        fields=["company", "start_datetime", "end_datetime"], name="calendar_ev_company_b3cb99_idx"
                    ),
                    models.Index(fields=["uuid"], name="calendar_ev_uuid_ec214f_idx"),
                ],
            },
        ),
    ]
