# Generated by Django 5.0.14 on 2026-03-10 19:18

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0014_company_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("daily", "Diária"),
                            ("overtime", "Hora Extra"),
                            ("bonus", "Bônus"),
                            ("discount", "Desconto"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("competence_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("multiplier", models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                (
                    "payout_mode",
                    models.CharField(
                        choices=[("weekly", "Semanal"), ("weekday", "Dia da Semana"), ("monthly", "Mensal")],
                        db_index=True,
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("payout_weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("assigned", "Atribuído"),
                            ("paid", "Pago"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_earning_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earning_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("weekday", "Dia da Semana"),
                            ("monthly", "Mensal"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("closed", "Fechado"),
                            ("paid", "Pago"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("scheduled_pay_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=200)),
                (
                    "line_type",
                    models.CharField(
                        choices=[("earning", "Provento"), ("deduction", "Desconto"), ("provision", "Provisão")],
                        db_index=True,
                        default="earning",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="payroll.earningevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="payroll.payrollrun"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="earningevent",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="payroll.payrollrun",
            ),
        ),
        migrations.CreateModel(
            name="CompensationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salary_monthly", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("weekly_hours", models.PositiveSmallIntegerField(default=44)),
                ("hourly_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                (
                    "extras_payout_mode",
                    models.CharField(
                        choices=[("weekly", "Semanal"), ("weekday", "Dia da Semana"), ("monthly", "Mensal")],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("extras_weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["company", "user"], name="payroll_com_company_ed6e7a_idx")],
                "unique_together": {("company", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["company", "period_start", "period_end"], name="payroll_pay_company_b7bace_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["company", "scheduled_pay_date"], name="payroll_pay_company_147e27_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["company", "status"], name="payroll_pay_company_32e802_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["company", "payroll_run"], name="payroll_pay_company_911419_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["company", "user"], name="payroll_pay_company_37686d_idx"),
        ),
        migrations.AddIndex(
            model_name="earningevent",
            index=models.Index(fields=["company", "competence_date"], name="payroll_ear_company_e2c909_idx"),
        ),
        migrations.AddIndex(
            model_name="earningevent",
            index=models.Index(fields=["company", "user", "competence_date"], name="payroll_ear_company_9c4ba9_idx"),
        ),
        migrations.AddIndex(
            model_name="earningevent",
            index=models.Index(fields=["company", "status"], name="payroll_ear_company_6fcd89_idx"),
        ),
    ]
