# Generated by Django 5.0.14 on 2026-03-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_alter_earningevent_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="earningevent",
            name="breakdown",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
