# Generated by Django 5.0.14 on 2026-03-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_company_soft_delete"),
        ("payroll", "0003_earningevent_breakdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirteenthPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                ("installment", models.PositiveSmallIntegerField(db_index=True)),
                ("pay_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thirteenth_payouts",
                        to="payroll.earningevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thirteenth_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirteenthAccrual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                ("month", models.PositiveSmallIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("salary_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("accrued", "Provisionado"), ("paid", "Pago"), ("cancelled", "Cancelado")],
                        db_index=True,
                        default="accrued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thirteenth_accruals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accruals",
                        to="payroll.thirteenthpayout",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="thirteenthpayout",
            index=models.Index(fields=["company", "year", "installment"], name="payroll_thi_company_648056_idx"),
        ),
        migrations.AddIndex(
            model_name="thirteenthpayout",
            index=models.Index(fields=["company", "pay_date"], name="payroll_thi_company_b12e13_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="thirteenthpayout",
            unique_together={("company", "user", "year", "installment")},
        ),
        migrations.AddIndex(
            model_name="thirteenthaccrual",
            index=models.Index(fields=["company", "user", "year", "month"], name="payroll_thi_company_c6317a_idx"),
        ),
        migrations.AddIndex(
            model_name="thirteenthaccrual",
            index=models.Index(fields=["company", "year", "status"], name="payroll_thi_company_8ba2d1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="thirteenthaccrual",
            unique_together={("company", "user", "year", "month")},
        ),
    ]
