# Generated by Django 5.0.14 on 2026-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_thirteenthpayout_thirteenthaccrual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='employee_signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employee_signature_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
