# Generated by Django 5.0.14 on 2026-03-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar", "0001_initial"),
        ("core", "0014_company_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#000000", max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_categories",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Category",
                "verbose_name_plural": "Financial Categories",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, help_text="Valor da transação", max_digits=12)),
                ("type", models.CharField(choices=[("in", "Receita"), ("out", "Despesa")], max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("paid", "Pago"),
                            ("overdue", "Atrasado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(help_text="Data de vencimento")),
                ("payment_date", models.DateField(blank=True, help_text="Data do pagamento efetivo", null=True)),
                ("competence_date", models.DateField(help_text="Data de competência (mês de referência)")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                    ),
                ),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="calendar.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "indexes": [
                    models.Index(fields=["company", "competence_date"], name="finance_tra_company_82e797_idx"),
                    models.Index(fields=["company", "status"], name="finance_tra_company_721a4d_idx"),
                    models.Index(fields=["company", "type"], name="finance_tra_company_ff94e0_idx"),
                ],
            },
        ),
    ]
