# Generated by Django 5.0.14 on 2026-03-10 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_company_soft_delete"),
        ("finance", "0002_category_created_by_category_is_shared"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_shared", True)),
                fields=("company", "name"),
                name="finance_category_unique_shared_name_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_shared", False)),
                fields=("company", "created_by", "name"),
                name="finance_category_unique_personal_name_per_user",
            ),
        ),
    ]
