# Generated by Django 5.2.11 on 2026-02-05 20:14

import secrets

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_company_onboarding_completed_company_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=500, verbose_name="URL de Destino")),
                (
                    "secret",
                    models.CharField(default=secrets.token_hex, max_length=255, verbose_name="Segredo de Assinatura"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("events", models.JSONField(default=list, verbose_name="Eventos Subscritos")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="Descrição/Nome")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.company")),
            ],
            options={
                "verbose_name": "Assinatura de Webhook",
                "verbose_name_plural": "Assinaturas de Webhook",
                "ordering": ["-created_at"],
            },
        ),
    ]
