# Generated by Django 5.0.14 on 2026-03-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('request_payload', models.JSONField()),
                ('response_body', models.TextField(blank=True, null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
