# Generated by Django 5.0.14 on 2026-01-29 04:23

import django.contrib.auth.models
from django.db import migrations

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_manager_name": "all_objects",
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.TenantUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
