# Generated by Django 5.2.10 on 2026-01-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserThemePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme_palette",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("django-green", "Django Green"),
                            ("ocean-blue", "Ocean Blue"),
                            ("royal-purple", "Royal Purple"),
                            ("sunset-orange", "Sunset Orange"),
                            ("forest-green", "Forest Green"),
                            ("slate-gray", "Slate Gray"),
                        ],
                        help_text="Paleta escolhida pelo usuário (null = usa tema da empresa)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "use_tenant_theme",
                    models.BooleanField(
                        default=True, help_text="Se True, ignora theme_palette e usa o tema da empresa"
                    ),
                ),
                (
                    "dark_mode_preference",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                        default="system",
                        help_text="Preferência de modo escuro (independente do tema)",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Theme Preference",
                "verbose_name_plural": "User Theme Preferences",
            },
        ),
    ]
