# Generated by Django 5.2.11 on 2026-02-09 13:52

import django.contrib.auth.models
from django.db import migrations

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_manager_name": "objects", "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
                ("tenant_objects", apps.accounts.models.TenantUserManager()),
            ],
        ),
    ]
