# Generated by Django 5.0.14 on 2026-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_last_seen"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0010_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["company", "last_seen"], name="user_company_last_seen_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["company", "role"], name="user_company_role_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_seen"], name="user_last_seen_idx"),
        ),
    ]
