# Generated by Django 5.2.11 on 2026-02-24 20:00

import django.contrib.auth.models
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_manager_name": "all_objects", "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.TenantUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("busy", "Ocupado"), ("offline", "Offline")],
                default="online",
                help_text="Status de presença do usuário",
                max_length=20,
            ),
        ),
    ]
