# Generated by Django 5.2.11 on 2026-03-02 11:42

from django.db import migrations, models

import shared_kernel.utils


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_options_alter_user_managers_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to=shared_kernel.utils.TenantUploadTo("avatars"),
            ),
        ),
    ]
