# Generated by Django 5.0.14 on 2026-03-17

from django.db import migrations


def add_comment_moderate_permission(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    roles = Role.objects.all()
    for role in roles:
        perms = list(role.permissions or [])
        if "*" in perms:
            continue
        if "articles.article_manage" in perms and "articles.comment_moderate" not in perms:
            perms.append("articles.comment_moderate")
            role.permissions = perms
            role.save(update_fields=["permissions"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_user_bio"),
    ]

    operations = [
        migrations.RunPython(add_comment_moderate_permission, migrations.RunPython.noop),
    ]
