# Generated by Django 5.0.14 on 2026-03-17

from django.db import migrations


def drop_article_manage_legacy_permission(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    roles = Role.objects.all()
    for role in roles:
        perms = list(role.permissions or [])
        if "*" in perms:
            continue
        if "articles.article_manage" not in perms:
            continue

        if "articles.comment_moderate" not in perms:
            perms.append("articles.comment_moderate")

        perms = [p for p in perms if p != "articles.article_manage"]
        role.permissions = perms
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_role_comment_moderate_compat"),
    ]

    operations = [
        migrations.RunPython(drop_article_manage_legacy_permission, migrations.RunPython.noop),
    ]
