# Generated by Django 5.0.14 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_articles_article_manage_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notify_comment_moderation",
                    models.BooleanField(
                        default=True,
                        help_text="Receber notificações de moderação (comentários/repostas pendentes)",
                    ),
                ),
                (
                    "notify_reply_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Receber notificações quando uma resposta ao seu comentário for aprovada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Preference",
                "verbose_name_plural": "User Notification Preferences",
            },
        ),
    ]
