# Generated by Django 5.0.14 on 2026-03-18

from django.db import migrations, models


def copy_preferences(apps, schema_editor):
    Pref = apps.get_model("accounts", "UserNotificationPreference")
    for p in Pref.objects.all():
        old_mod = getattr(p, "notify_comment_moderation", True)
        old_reply = getattr(p, "notify_reply_approved", True)
        p.notify_moderation_comment_pending = old_mod
        p.notify_moderation_reply_pending = old_mod
        p.notify_reply_approved_single = old_reply
        p.notify_reply_approved_thread = old_reply
        p.save(
            update_fields=[
                "notify_moderation_comment_pending",
                "notify_moderation_reply_pending",
                "notify_reply_approved_single",
                "notify_reply_approved_thread",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_usernotificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpreference",
            name="notify_moderation_comment_pending",
            field=models.BooleanField(
                default=True, help_text="Receber notificações quando houver comentários pendentes"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="notify_moderation_reply_pending",
            field=models.BooleanField(default=True, help_text="Receber notificações quando houver respostas pendentes"),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="notify_reply_approved_single",
            field=models.BooleanField(
                default=True, help_text="Receber notificação quando uma resposta ao seu comentário for aprovada"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="notify_reply_approved_thread",
            field=models.BooleanField(
                default=True, help_text="Receber notificação quando replies forem aprovadas na sua thread"
            ),
        ),
        migrations.RunPython(copy_preferences, migrations.RunPython.noop),
        migrations.RemoveField(model_name="usernotificationpreference", name="notify_comment_moderation"),
        migrations.RemoveField(model_name="usernotificationpreference", name="notify_reply_approved"),
    ]
