# Generated by Django 5.0.14 on 2026-03-30 17:45

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='crm_contact_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='crm_contact_email_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='crm_deal_title_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
