# Generated by Django 5.0.14 on 2026-03-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_crm_contact_name_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
