# Generated by Django 5.0.14 on 2026-04-02 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_columns_and_deal_links(apps, schema_editor):
    Stage = apps.get_model("crm", "Stage")
    Column = apps.get_model("crm", "Column")
    Deal = apps.get_model("crm", "Deal")

    stage_to_column = {}

    for stage in Stage.objects.select_related("pipeline", "company").all():
        column = Column.objects.create(
            company=stage.company,
            pipeline=stage.pipeline,
            title=stage.name,
            order=stage.order,
            legacy_stage=stage,
        )
        stage_to_column[stage.id] = column.id

    for deal in Deal.objects.all():
        column_id = stage_to_column.get(deal.stage_id)
        if column_id:
            Deal.objects.filter(id=deal.id).update(column_id=column_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('crm', '0004_deal_custom_fields_dealactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='integration_source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#CBD5E1', max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('legacy_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='crm.stage')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='crm.column'),
        ),
        migrations.RunPython(backfill_columns_and_deal_links, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'column'], name='crm_deal_company_a2da05_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'external_id'], name='crm_deal_company_4af05c_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['company', 'pipeline', 'order'], name='crm_column_company_243e09_idx'),
        ),
    ]
